import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Mail, User, MessageSquare, Send, CheckCircle } from 'lucide-react';
import { showToast } from '@/components/common/Toast';
import { saveContactMessage } from '@/services/storageService';

export default function ContactPage() {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [consent, setConsent] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({}); const [sent, setSent] = useState(false); const [submitting, setSubmitting] = useState(false);
  const validate = () => { const errs: Record<string,string> = {}; if (!name.trim()) errs.name='Acest câmp este obligatoriu.'; if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) errs.email='Introdu un email valid.'; if (!message.trim()) errs.message='Acest câmp este obligatoriu.'; if (!consent) errs.consent='Este necesar acordul pentru prelucrarea datelor.'; setErrors(errs); return Object.keys(errs).length===0; };
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); if (!validate()) return; setSubmitting(true); try { await saveContactMessage({ name, email, message, consent }); showToast('Mesajul tău a fost trimis cu succes.','success'); setSent(true); setName(''); setEmail(''); setMessage(''); setConsent(false); setErrors({}); } catch (err) { showToast(err instanceof Error ? err.message : 'Mesajul nu a putut fi trimis.','error'); } finally { setSubmitting(false); } };
  return <div className="container-page py-12"><div className="max-w-xl mx-auto"><div className="text-center mb-8"><h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white">Contactează-ne</h1><p className="mt-2 text-slate-500 dark:text-slate-400">Ai întrebări sau sugestii? Scrie-ne și îți răspundem cât mai curând.</p></div>{sent && <div className="mb-6 flex items-center gap-3 rounded-xl bg-success-50 border border-success-100 p-4 text-success-700"><CheckCircle className="h-5 w-5 shrink-0" /><p className="text-sm font-medium">Mesajul tău a fost înregistrat. Îți vom răspunde la adresa de email introdusă.</p></div>}<form onSubmit={handleSubmit} className="card p-6 sm:p-8 space-y-5"><div><label className="label-field flex items-center gap-1.5"><User className="h-4 w-4 text-brand-500"/>Nume *</label><input type="text" value={name} onChange={(e)=>setName(e.target.value)} className="input-field" placeholder="Numele tău" />{errors.name&&<p className="mt-1 text-xs text-error-600">{errors.name}</p>}</div><div><label className="label-field flex items-center gap-1.5"><Mail className="h-4 w-4 text-brand-500"/>Email *</label><input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} className="input-field" placeholder="exemplu@email.ro" />{errors.email&&<p className="mt-1 text-xs text-error-600">{errors.email}</p>}</div><div><label className="label-field flex items-center gap-1.5"><MessageSquare className="h-4 w-4 text-brand-500"/>Mesaj *</label><textarea value={message} onChange={(e)=>setMessage(e.target.value)} rows={5} className="input-field resize-none" placeholder="Scrie mesajul tău aici..." />{errors.message&&<p className="mt-1 text-xs text-error-600">{errors.message}</p>}</div><label className="flex items-start gap-3 text-xs text-slate-600 dark:text-slate-300"><input type="checkbox" checked={consent} onChange={(e)=>setConsent(e.target.checked)} className="mt-0.5 h-4 w-4 rounded border-slate-300 text-brand-600"/><span>Sunt de acord ca datele introduse să fie prelucrate pentru soluționarea mesajului, conform <Link to="/confidentialitate" className="font-semibold text-brand-600 hover:underline">Politicii de confidențialitate</Link>.</span></label>{errors.consent&&<p className="-mt-3 text-xs text-error-600">{errors.consent}</p>}<button type="submit" disabled={submitting} className="btn-primary w-full text-base py-4"><Send className="h-5 w-5"/>{submitting?'Se trimite...':'Trimite mesajul'}</button></form></div></div>;
}
